#Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.gohelpfund.api.v1: WARN
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/