security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8764/api/v1/auth/user

spring:
  jackson:
    default-property-inclusion: NON_NULL
  zipkin:
    baseUrl:  localhost:9411
  hateoas:
    use-hal-as-default-json-media-type: false
  cloud:
    stream:
      bindings:
        inboundFundraiserChanges:
          destination: fundraiserChangeTopic
          content-type: application/json
          group: campaignGroup
        binder:
          zkNodes: localhost
          brokers: localhost
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.gohelpfund.api.v1: WARN
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE