version: '2'
services:
  configserver:
    image: gohelpfund/ghf-confsvr:gohelpfund
    ports:
    - "8888:8888"
    environment:
      SERVER_PORT: "8888"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  database:
    image: postgres:9.5
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB:       "gohelpfund_local"
  campaignservice:
    image: gohelpfund/ghf-campaign-service:gohelpfund
    ports:
    - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
