version: '2'

networks:
  default:
    driver: bridge

services:
  eureka-server:
    image:   gohelpfund/ghf-eureka-server:${BUILD_NAME}
    ports:
      -                           "8761:8761"
    environment:
      PROFILE:                  "dev-api"
    networks:
      default:
        aliases:
          - eureka-server

  config-server:
    image: gohelpfund/ghf-config-server:${BUILD_NAME}
    ports:
      -                           "8762:8762"
    links:
      - "eureka-server:eureka-server"
    networks:
      default:
        aliases:
          - config-server
    environment:
      PROFILE:                  "dev-api"
      SERVER_PORT:              "8762"
      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      ENCRYPT_KEY:              $SYMMETRIC_ENCRYPTION_KEY
      GIT_URI:                  $GIT_CONFIG_REPO_URI
      GIT_USERNAME:             $GIT_CONFIG_REPO_USERNAME
      GIT_PASSWORD:             $GIT_CONFIG_REPO_PASSWORD

  zuul-server:
    image: gohelpfund/ghf-zuul-server:${BUILD_NAME}
    ports:
      -                           "443:8763"
    links:
      - "eureka-server:eureka-server"
      - "config-server:config-server"
      - "authentication-service:authentication-service"
      - "fundraiser-service:fundraiser-service"
      - "campaign-service:campaign-service"
    networks:
      default:
        aliases:
          - zuul-server
    environment:
      PROFILE:                  "dev-api"
      SERVER_PORT:              "8763"
      ANALYTICS_KEY:            "84rYLp2FgMyG0zfFkNpFSQMLACBYmFZa"
      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
      ZIPKIN_URI:               "http://zipkin-server:9411"
      CONFIGSERVER_URI:         "http://config-server:8762"
      ZIPKIN_PORT:              "9411"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8762"
      CATEGORYSERVERNEW_PORT:   "9102"

  authentication-service:
    image: gohelpfund/ghf-authentication-service:${BUILD_NAME}
    ports:
      -                           "8764:8764"
    links:
      - "config-server:config-server"
      - "eureka-server:eureka-server"
    networks:
      default:
        aliases:
          - authentication-service
    environment:
      PROFILE:                  "dev-api"
      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
      CONFIGSERVER_URI:         "http://config-server:8762"
      CAMPAIGN_SERVICE_PORT:    "9100"
      SERVER_PORT:              "8764"
      EUREKASERVER_PORT:        "8761"
      CONFIGSERVER_PORT:        "8762"
      ZUULSERVER_PORT:          "8763"
      DATABASESERVER_PORT:      "5432"
      ENCRYPT_KEY:              $SYMMETRIC_ENCRYPTION_KEY

  donation-service:
    image: gohelpfund/ghf-donation-service:${BUILD_NAME}
    ports:
      -                           "9000:9000"
    links:
      - "authentication-service:authentication-service"
      - "config-server:config-server"
      - "eureka-server:eureka-server"
    networks:
      default:
        aliases:
          - donation-service
    environment:
      SERVER_PORT:              "9000"
      PROFILE:                  "dev-api"
      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
      CONFIGSERVER_URI:         "http://config-server:8762"
      AUTHSERVER_URI:           "http://authentication-service:8764/api/v1/auth/user"
      EUREKASERVER_PORT:        "8761"
      CONFIGSERVER_PORT:        "8762"
      ZUULSERVER_PORT:          "8763"
      AUTHSERVER_PORT:          "8764"
      DATABASESERVER_PORT:      "5432"
      ZKSERVER_PORT:            "2181"
      ENCRYPT_KEY:              $SYMMETRIC_ENCRYPTION_KEY

  campaign-service:
    image: gohelpfund/ghf-campaign-service:${BUILD_NAME}
    ports:
      -                           "9100:9100"
    links:
      - "authentication-service:authentication-service"
      - "donation-service:donation-service"
      - "config-server:config-server"
      - "eureka-server:eureka-server"
      - "kafka-server:kafka-server"
      - "redis:redis"
    networks:
      default:
        aliases:
          - campaign-service
    environment:
      PROFILE:                  "dev-api"
      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
      ZIPKIN_URI:               "http://zipkin-server:9411"
      CONFIGSERVER_URI:         "http://config-server:8762"
      KAFKASERVER_URI:          "kafka-server"
      ZKSERVER_URI:             "kafka-server"
      AUTHSERVER_URI:           "http://authentication-service:8764/api/v1/auth/user"
      ZIPKIN_PORT:              "9411"
      SERVER_PORT:              "9100"
      KAFKASERVER_PORT:         "9092"
      DONATION_PORT:            "9000"
      EUREKASERVER_PORT:        "8761"
      CONFIGSERVER_PORT:        "8762"
      ZUULSERVER_PORT:          "8763"
      AUTHSERVER_PORT:          "8764"
      REDIS_PORT:               "6379"
      DATABASESERVER_PORT:      "5432"
      ZKSERVER_PORT:            "2181"
      ENCRYPT_KEY:              $SYMMETRIC_ENCRYPTION_KEY

  fundraiser-service:
    image: gohelpfund/ghf-fundraiser-service:${BUILD_NAME}
    ports:
      -                           "9200:9200"
    links:
      - "authentication-service:authentication-service"
      - "donation-service:donation-service"
      - "config-server:config-server"
      - "eureka-server:eureka-server"
      - "kafka-server:kafka-server"
    networks:
      default:
        aliases:
          - fundraiser-service
    environment:
      PROFILE:                  "dev-api"
      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
      ZIPKIN_URI:               "http://zipkin-server:9411"
      CONFIGSERVER_URI:         "http://config-server:8762"
      KAFKASERVER_URI:          "kafka-server"
      ZKSERVER_URI:             "kafka-server"
      AUTHSERVER_URI:           "http://authentication-service:8764/api/v1/auth/user"
      ZIPKIN_PORT:              "9411"
      SERVER_PORT:              "9200"
      KAFKASERVER_PORT:         "9092"
      DONATION_PORT:            "9000"
      EUREKASERVER_PORT:        "8761"
      CONFIGSERVER_PORT:        "8762"
      ZUULSERVER_PORT:          "8763"
      AUTHSERVER_PORT:          "8764"
      DATABASESERVER_PORT:      "5432"
      ZKSERVER_PORT:            "2181"
      ENCRYPT_KEY:              $SYMMETRIC_ENCRYPTION_KEY

  kafka-server:
    image: spotify/kafka
    ports:
      -                           "2181:2181"
      -                           "9092:9092"
    networks:
      default:
        aliases:
          - kafka-server

  redis:
    image: redis:alpine
    ports:
      -                           "6379:6379"
    networks:
      default:
        aliases:
          - redis