eureka-server:
  image:   gohelpfund/ghf-eureka-server:latest
  mem_limit: 353741824
  ports:
  - "8761:8761"
  environment:
    PROFILE: "dev-api"

config-server:
  image: gohelpfund/ghf-config-server:latest
  mem_limit: 303741824
  ports:
  - "8762:8762"
  links:
  - "eureka-server:eureka-server"
  environment:
    PROFILE: "dev-api"
    SERVER_PORT: "8762"
    EUREKASERVER_URI: "http://eureka-server:8761/eureka/"
    EUREKASERVER_PORT: "8761"
    ENCRYPT_KEY: "IMSYMMETRIC"

zuul-server:
  image: gohelpfund/ghf-zuul-server:latest
  mem_limit: 353741824
  ports:
  - "80:8763"
  links:
  - "eureka-server:eureka-server"
  - "config-server:config-server"
  - "authentication-service:authentication-service"
  - "fundraiser-service:fundraiser-service"
  - "campaign-service:campaign-service"
  environment:
    PROFILE: "dev-api"
    SERVER_PORT: "8763"
    EUREKASERVER_URI: "http://eureka-server:8761/eureka/"
    CONFIGSERVER_URI: "http://config-server:8762"
    EUREKASERVER_PORT:        "8761"
    DATABASESERVER_PORT:      "5432"
    CONFIGSERVER_PORT:        "8762"
    CATEGORYSERVERNEW_PORT:   "9102"

database:
  image: postgres:9.5
  mem_limit: 103741824
  ports:
  - "5432:5432"
  environment:
    PROFILE: "dev-api"
    POSTGRES_USER: "postgres_dev"
    POSTGRES_PASSWORD:  "p0stgr@s_dev"
    POSTGRES_DB: "gohelpfund_dev"

authentication-service:
  image: gohelpfund/ghf-authentication-service:latest
  mem_limit: 353741824
  ports:
  - "8764:8764"
  links:
  - "config-server:config-server"
  - "database:database"
  - "eureka-server:eureka-server"
  environment:
    PROFILE: "dev-api"
    EUREKASERVER_URI:   "http://eureka-server:8761/eureka/"
    CONFIGSERVER_URI:   "http://config-server:8762"
    SERVER_PORT:                   "8764"
    EUREKASERVER_PORT:             "8761"
    CONFIGSERVER_PORT:             "8762"
    ZUULSERVER_PORT:               "8763"
    DATABASESERVER_PORT:           "5432"
    ENCRYPT_KEY:            "IMSYMMETRIC"

campaign-service:
  image: gohelpfund/ghf-campaign-service:latest
  mem_limit: 353741824
  ports:
  - "9100:9100"
  links:
  - "config-server:config-server"
  - "database:database"
  - "eureka-server:eureka-server"
  environment:
    PROFILE: "dev-api"
    EUREKASERVER_URI:   "http://eureka-server:8761/eureka/"
    CONFIGSERVER_URI:   "http://config-server:8762"
    SERVER_PORT:                   "9100"
    EUREKASERVER_PORT:             "8761"
    CONFIGSERVER_PORT:             "8762"
    ZUULSERVER_PORT:               "8763"
    DATABASESERVER_PORT:           "5432"
    ENCRYPT_KEY:            "IMSYMMETRIC"

fundraiser-service:
  image: gohelpfund/ghf-fundraiser-service:latest
  mem_limit: 353741824
  ports:
  - "9200:9200"
  links:
  - "config-server:config-server"
  - "database:database"
  - "eureka-server:eureka-server"
  environment:
    PROFILE: "dev-api"
    EUREKASERVER_URI: "http://eureka-server:8761/eureka/"
    CONFIGSERVER_URI: "http://config-server:8762"
    SERVER_PORT:              "9200"
    EUREKASERVER_PORT:        "8761"
    CONFIGSERVER_PORT:        "8762"
    ZUULSERVER_PORT:          "8763"
    DATABASESERVER_PORT:      "5432"
    ENCRYPT_KEY:       "IMSYMMETRIC"
kafka-server:
  image: spotify/kafka
  mem_limit: 353741824
  ports:
  - 2181:2181
  - 9092:9092