version: '2'
services:
  eureka-server:
    image:   gohelpfund/ghf-eureka-server:${BUILD_NAME}
    cpu_shares: 100
    mem_limit: 524288000
    ports:
    -                           "8761:8761"
    environment:
      PROFILE:                  "dev-api"
    networks:
      main:
        aliases:
          - eureka-server

  config-server:
    image: gohelpfund/ghf-config-server:${BUILD_NAME}
    cpu_shares: 100
    mem_limit: 524288000
    ports:
    -                           "8762:8762"
    networks:
      main:
        aliases:
          - config-server
    environment:
      PROFILE:                  "dev-api"
      SERVER_PORT:              "8762"
      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      ENCRYPT_KEY:              "IMSYMMETRIC"
      GIT_URI:                  $GIT_CONFIG_REPO_URI
      GIT_USERNAME:             $GIT_CONFIG_REPO_USERNAME
      GIT_PASSWORD:             $GIT_CONFIG_REPO_PASSWORD

  zuul-server:
    image: gohelpfund/ghf-zuul-server:${BUILD_NAME}
    cpu_shares: 100
    mem_limit: 524288000
    ports:
    -                           "443:8763"
    networks:
      main:
        aliases:
          - zuul-server
    environment:
      PROFILE:                  "dev-api"
      SERVER_PORT:              "8763"
      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
      ZIPKIN_URI:               "http://zipkin-server:9411"
      CONFIGSERVER_URI:         "http://config-server:8762"
      ZIPKIN_PORT:              "9411"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8762"
      CATEGORYSERVERNEW_PORT:   "9102"

  database:
    image: postgres:9.5
    cpu_shares: 100
    mem_limit: 224288000
    networks:
      main:
        aliases:
          - database
    ports:
    -                           "5432:5432"
    environment:
      PROFILE:                  "dev-api"
      POSTGRES_USER:            "postgres_dev"
      POSTGRES_PASSWORD:        "p0stgr@s_dev"
      POSTGRES_DB:              "gohelpfund_dev"

  authentication-service:
    image: gohelpfund/ghf-authentication-service:${BUILD_NAME}
    cpu_shares: 200
    mem_limit: 753741824
    ports:
    -                           "8764:8764"
    networks:
      main:
        aliases:
          - authentication-service
    environment:
      PROFILE:                  "dev-api"
      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
      CONFIGSERVER_URI:         "http://config-server:8762"
      CAMPAIGN_SERVICE_PORT:    "9100"
      SERVER_PORT:              "8764"
      EUREKASERVER_PORT:        "8761"
      CONFIGSERVER_PORT:        "8762"
      ZUULSERVER_PORT:          "8763"
      DATABASESERVER_PORT:      "5432"
      ENCRYPT_KEY:              "IMSYMMETRIC"

  donation-service:
    image: gohelpfund/ghf-donation-service:${BUILD_NAME}
    cpu_shares: 200
    mem_limit: 524288000
    ports:
      -                           "9000:9000"
    networks:
      main:
        aliases:
          - donation-service
    environment:
      SERVER_PORT:              "9000"
      PROFILE:                  "dev-api"
      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
      CONFIGSERVER_URI:         "http://config-server:8762"
      AUTHSERVER_URI:           "http://authentication-service:8764/api/v1/auth/user"
      EUREKASERVER_PORT:        "8761"
      CONFIGSERVER_PORT:        "8762"
      ZUULSERVER_PORT:          "8763"
      AUTHSERVER_PORT:          "8764"
      DATABASESERVER_PORT:      "5432"
      ZKSERVER_PORT:            "2181"
      ENCRYPT_KEY:              "IMSYMMETRIC"

  campaign-service:
    image: gohelpfund/ghf-campaign-service:${BUILD_NAME}
    cpu_shares: 200
    mem_limit: 953741824
    ports:
    -                           "9100:9100"
    networks:
      main:
        aliases:
          - campaign-service
    environment:
      PROFILE:                  "dev-api"
      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
      ZIPKIN_URI:               "http://zipkin-server:9411"
      CONFIGSERVER_URI:         "http://config-server:8762"
      KAFKASERVER_URI:          "kafka-server"
      ZKSERVER_URI:             "kafka-server"
      AUTHSERVER_URI:           "http://authentication-service:8764/api/v1/auth/user"
      ZIPKIN_PORT:              "9411"
      SERVER_PORT:              "9100"
      KAFKASERVER_PORT:         "9092"
      DONATION_PORT:            "9000"
      EUREKASERVER_PORT:        "8761"
      CONFIGSERVER_PORT:        "8762"
      ZUULSERVER_PORT:          "8763"
      AUTHSERVER_PORT:          "8764"
      REDIS_PORT:               "6379"
      DATABASESERVER_PORT:      "5432"
      ZKSERVER_PORT:            "2181"
      ENCRYPT_KEY:              "IMSYMMETRIC"

  fundraiser-service:
    image: gohelpfund/ghf-fundraiser-service:${BUILD_NAME}
    cpu_shares: 200
    mem_limit: 524288000
    ports:
    -                           "9200:9200"
    networks:
      main:
        aliases:
          - fundraiser-service
    environment:
      PROFILE:                  "dev-api"
      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
      ZIPKIN_URI:               "http://zipkin-server:9411"
      CONFIGSERVER_URI:         "http://config-server:8762"
      KAFKASERVER_URI:          "kafka-server"
      ZKSERVER_URI:             "kafka-server"
      AUTHSERVER_URI:           "http://authentication-service:8764/api/v1/auth/user"
      ZIPKIN_PORT:              "9411"
      SERVER_PORT:              "9200"
      KAFKASERVER_PORT:         "9092"
      DONATION_PORT:            "9000"
      EUREKASERVER_PORT:        "8761"
      CONFIGSERVER_PORT:        "8762"
      ZUULSERVER_PORT:          "8763"
      AUTHSERVER_PORT:          "8764"
      DATABASESERVER_PORT:      "5432"
      ZKSERVER_PORT:            "2181"
      ENCRYPT_KEY:              "IMSYMMETRIC"

  kafka-server:
    image: spotify/kafka
    cpu_shares: 100
    mem_limit: 753741824
    ports:
    -                           "2181:2181"
    -                           "9092:9092"
    networks:
      main:
        aliases:
          - kafka-server

  redis:
    image: redis:alpine
    cpu_shares: 100
    mem_limit: 353741824
    ports:
    -                           "6379:6379"
    networks:
      main:
        aliases:
          - redis

networks:
  main:
