config-server:
  image: gohelpfund/ghf-config-server:latest
  mem_limit: 203741824
  ports:
  - "8888:8888"
  environment:
    PROFILE: "dev-api"
    SERVER_PORT: "8888"
    ENCRYPT_KEY: "IMSYMMETRIC"
database:
  image: postgres:9.5
  mem_limit: 103741824
  ports:
  - "5432:5432"
  environment:
    PROFILE: "dev-api"
    POSTGRES_USER: "postgres_dev"
    POSTGRES_PASSWORD:  "p0stgr@s_dev"
    POSTGRES_DB: "gohelpfund_dev"
campaignservice:
  image: gohelpfund/ghf-campaign-service:latest
  mem_limit: 253741824
  links:
  - "config:config"
  - "database:database"
  ports:
  - "5555:5555"
  environment:
    PROFILE: "dev-api"
    SERVER_PORT: "5555"
    CONFIGSERVER_URI: "http://config:8888"
    CONFIGSERVER_PORT:   "8888"
    DATABASESERVER_PORT: "5432"
    ENCRYPT_KEY: "IMSYMMETRIC"