eureka-server:
  image:   gohelpfund/ghf-eureka-server:${BUILD_NAME}
  mem_limit: 353741824
  ports:
  -                           "8761:8761"
  environment:
    PROFILE:                  "prod-api"

config-server:
  image: gohelpfund/ghf-config-server:${BUILD_NAME}
  mem_limit: 303741824
  ports:
  -                           "8762:8762"
  links:
  -                           "eureka-server:eureka-server"
  environment:
    PROFILE:                  "prod-api"
    SERVER_PORT:              "8762"
    EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
    EUREKASERVER_PORT:        "8761"
    ENCRYPT_KEY:              "IMSYMMETRIC"
    GIT_URI:                  $GIT_CONFIG_REPO_URI
    GIT_USERNAME:             $GIT_CONFIG_REPO_USERNAME
    GIT_PASSWORD:             $GIT_CONFIG_REPO_PASSWORD

zipkin-server:
  image: gohelpfund/ghf-zipkin-server:${BUILD_NAME}
  mem_limit: 253741824
  ports:
  -                           "9411:9411"
  environment:
    PROFILE:                  "prod-api"
    SERVER_PORT:              "9411"
    ZIPKIN_URI:               "http://zipkin-server:9411"

zuul-server:
  image: gohelpfund/ghf-zuul-server:${BUILD_NAME}
  mem_limit: 353741824
  ports:
  -                           "443:8763"
  links:
  -                           "zipkin-server:zipkin-server"
  -                           "eureka-server:eureka-server"
  -                           "config-server:config-server"
  -                           "authentication-service:authentication-service"
  -                           "fundraiser-service:fundraiser-service"
  -                           "campaign-service:campaign-service"
  environment:
    PROFILE:                  "prod-api"
    SERVER_PORT:              "8763"
    EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
    ZIPKIN_URI:               "http://zipkin-server:9411"
    CONFIGSERVER_URI:         "http://config-server:8762"
    ZIPKIN_PORT:              "9411"
    EUREKASERVER_PORT:        "8761"
    DATABASESERVER_PORT:      "5432"
    CONFIGSERVER_PORT:        "8762"
    CATEGORYSERVERNEW_PORT:   "9102"

database:
  image: postgres:9.5
  mem_limit: 103741824
  ports:
  -                           "5432:5432"
  environment:
    PROFILE:                  "prod-api"
    POSTGRES_USER:            "postgres_prod"
    POSTGRES_PASSWORD:        "p0stgr@s_prod"
    POSTGRES_DB:              "gohelpfund_prod"

authentication-service:
  image: gohelpfund/ghf-authentication-service:${BUILD_NAME}
  mem_limit: 353741824
  ports:
  -                           "8764:8764"
  links:
  -                           "config-server:config-server"
  -                           "database:database"
  -                           "eureka-server:eureka-server"
  environment:
    PROFILE:                  "prod-api"
    EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
    CONFIGSERVER_URI:         "http://config-server:8762"
    SERVER_PORT:              "8764"
    EUREKASERVER_PORT:        "8761"
    CONFIGSERVER_PORT:        "8762"
    ZUULSERVER_PORT:          "8763"
    DATABASESERVER_PORT:      "5432"
    ENCRYPT_KEY:              "IMSYMMETRIC"

donation-service:
  image: gohelpfund/ghf-donation-service:${BUILD_NAME}
  mem_limit: 453741824
  ports:
    -                           "9000:9000"
  links:
    -                           "authentication-service:authentication-service"
    -                           "config-server:config-server"
    -                           "eureka-server:eureka-server"
  environment:
    SERVER_PORT:              "9000"
    PROFILE:                  "dev-api"
    EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
    CONFIGSERVER_URI:         "http://config-server:8762"
    AUTHSERVER_URI:           "http://authentication-service:8764/api/v1/auth/user"
    EUREKASERVER_PORT:        "8761"
    CONFIGSERVER_PORT:        "8762"
    ZUULSERVER_PORT:          "8763"
    AUTHSERVER_PORT:          "8764"
    DATABASESERVER_PORT:      "5432"
    ZKSERVER_PORT:            "2181"
    ENCRYPT_KEY:              "IMSYMMETRIC"

campaign-service:
  image: gohelpfund/ghf-campaign-service:${BUILD_NAME}
  mem_limit: 553741824
  ports:
  -                           "9100:9100"
  links:
  -                           "authentication-service:authentication-service"
  -                           "donation-service:donation-service"
  -                           "config-server:config-server"
  -                           "database:database"
  -                           "eureka-server:eureka-server"
  -                           "zipkin-server:zipkin-server"
  -                           "kafka-server:kafka-server"
  -                           "redis:redis"
  environment:
    PROFILE:                  "prod-api"
    EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
    ZIPKIN_URI:               "http://zipkin-server:9411"
    CONFIGSERVER_URI:         "http://config-server:8762"
    KAFKASERVER_URI:          "kafka-server"
    ZKSERVER_URI:             "kafka-server"
    AUTHSERVER_URI:           "http://authentication-service:8764/api/v1/auth/user"
    ZIPKIN_PORT:              "9411"
    SERVER_PORT:              "9100"
    KAFKASERVER_PORT:         "9092"
    DONATION_PORT:            "9000"
    EUREKASERVER_PORT:        "8761"
    CONFIGSERVER_PORT:        "8762"
    ZUULSERVER_PORT:          "8763"
    AUTHSERVER_PORT:          "8764"
    REDIS_PORT:               "6379"
    DATABASESERVER_PORT:      "5432"
    ZKSERVER_PORT:            "2181"
    ENCRYPT_KEY:              "IMSYMMETRIC"

fundraiser-service:
  image: gohelpfund/ghf-fundraiser-service:${BUILD_NAME}
  mem_limit: 453741824
  ports:
  -                           "9200:9200"
  links:
  -                           "authentication-service:authentication-service"
  -                           "donation-service:donation-service"
  -                           "config-server:config-server"
  -                           "database:database"
  -                           "zipkin-server:zipkin-server"
  -                           "eureka-server:eureka-server"
  -                           "kafka-server:kafka-server"
  environment:
    PROFILE:                  "prod-api"
    EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
    ZIPKIN_URI:               "http://zipkin-server:9411"
    CONFIGSERVER_URI:         "http://config-server:8762"
    KAFKASERVER_URI:          "kafka-server"
    ZKSERVER_URI:             "kafka-server"
    AUTHSERVER_URI:           "http://authentication-service:8764/api/v1/auth/user"
    ZIPKIN_PORT:              "9411"
    SERVER_PORT:              "9200"
    KAFKASERVER_PORT:         "9092"
    DONATION_PORT:            "9000"
    EUREKASERVER_PORT:        "8761"
    CONFIGSERVER_PORT:        "8762"
    ZUULSERVER_PORT:          "8763"
    AUTHSERVER_PORT:          "8764"
    DATABASESERVER_PORT:      "5432"
    ZKSERVER_PORT:            "2181"
    ENCRYPT_KEY:              "IMSYMMETRIC"

kafka-server:
  image: spotify/kafka
  mem_limit: 553741824
  ports:
  -                           "2181:2181"
  -                           "9092:9092"

redis:
  image: redis:alpine
  mem_limit: 253741824
  ports:
  -                           "6379:6379"

#logspout:
#  image: gliderlabs/logspout
#  mem_limit: 353741824
#  command: syslog://logs7.papertrailapp.com:11494
#  environment:
#    COMPOSE_CONVERT_WINDOWS_PATHS: 1
#  volumes:
#  - /var/run/docker.sock:/var/run/docker.sock