version: 1
task_definition:
  services:
    eureka-server:
      cpu_shares: 1023
      mem_limit: 2048MB
    config-server:
      cpu_shares: 1023
      mem_limit: 2048MB
    zuul-server:
      cpu_shares: 4096
      mem_limit: 5120MB
    authentication-service:
      cpu_shares: 1023
      mem_limit: 2470MB
    donation-service:
      cpu_shares: 3077
      mem_limit: 6144MB
    campaign-service:
      cpu_shares: 2048
      mem_limit: 5120MB
    fundraiser-service:
      cpu_shares: 2048
      mem_limit: 4096MB
    kafka-server:
      cpu_shares: 1023
      mem_limit: 2048MB
    redis:
      cpu_shares: 1023
      mem_limit: 2048MB