spring:
  jackson:
    default-property-inclusion: non_null
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
  mvc.throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false