version: '2'
services:
  eurekaserver:
    image:   gohelpfund/ghf-eurekasvr:latest
    ports:
    - "8761:8761"
  configserver:
    image: gohelpfund/ghf-confsvr:latest
    ports:
    - "8888:8888"
    environment:
      PROFILE: "local-api"
      SERVER_PORT: "8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  database:
    image: postgres:9.5
    ports:
    - "5432:5432"
    environment:
      PROFILE: "local-api"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr@s
      POSTGRES_DB: gohelpfund_local
  campaignservice:
    image: gohelpfund/ghf-campaign-service:latest
    ports:
    - "5555:5555"
    environment:
      PROFILE: "local-api"
      SERVER_PORT: "5555"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  fundraiserservice:
    image: gohelpfund/ghf-fundraiser-service:latest
    ports:
    - "5556:5556"
    environment:
      PROFILE: "local-api"
      SERVER_PORT: "5556"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"