version: '2'
services:
  eureka-server:
    image:   gohelpfund/ghf-eureka-server:${BUILD_NAME}
    mem_limit: 353741824
    ports:
    -                           "8761:8761"
    environment:
      PROFILE:                  "local-api"

  config-server:
    image: gohelpfund/ghf-config-server:${BUILD_NAME}
    mem_limit: 353741824
    ports:
    -                           "8762:8762"
    environment:
      PROFILE:                  "local-api"
      SERVER_PORT:              "8762"
      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      ENCRYPT_KEY:              "IMSYMMETRIC"
      GIT_URI:                  $GIT_CONFIG_REPO_URI
      GIT_USERNAME:             $GIT_CONFIG_REPO_USERNAME
      GIT_PASSWORD:             $GIT_CONFIG_REPO_PASSWORD

  zipkin-server:
    image: gohelpfund/ghf-zipkin-server:${BUILD_NAME}
    ports:
    -                           "9411:9411"
    environment:
      PROFILE:                  "local-api"
      SERVER_PORT:              "9411"
      ZIPKIN_URI:               "http://zipkin-server:9411"

  zuul-server:
    image: gohelpfund/ghf-zuul-server:${BUILD_NAME}
    mem_limit: 353741824
    ports:
    -                           "80:8763"
    environment:
      PROFILE:                  "local-api"
      SERVER_PORT:              "8763"
      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
      ZIPKIN_URI:               "http://zipkin-server:9411"
      CONFIGSERVER_URI:         "http://config-server:8762"
      ZIPKIN_PORT:              "9411"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8762"
      CATEGORYSERVERNEW_PORT:   "9102"

  database:
    image: postgres:9.5
    mem_limit: 253741824
    ports:
    -                           "5432:5432"
    environment:
      PROFILE:                  "local-api"
      POSTGRES_USER:            "postgres"
      POSTGRES_PASSWORD:        "p0stgr@s"
      POSTGRES_DB:              "gohelpfund_local"

  authentication-service:
    image: gohelpfund/ghf-authentication-service:${BUILD_NAME}
    mem_limit: 553741824
    ports:
    -                            "8764:8764"
    environment:
      PROFILE:                   "local-api"
      EUREKASERVER_URI:          "http://eureka-server:8761/eureka/"
      CONFIGSERVER_URI:          "http://config-server:8762"
      SERVER_PORT:               "8764"
      EUREKASERVER_PORT:         "8761"
      CONFIGSERVER_PORT:         "8762"
      ZUULSERVER_PORT:           "8763"
      DATABASESERVER_PORT:       "5432"
      ENCRYPT_KEY:               "IMSYMMETRIC"
#
#  fundraiser-service:
#    image: gohelpfund/ghf-fundraiser-service:${BUILD_NAME}
#    mem_limit: 353741824
#    ports:
#    -                           "9200:9200"
#    environment:
#      PROFILE:                  "local-api"
#      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
#      ZIPKIN_URI:               "http://zipkin-server:9411"
#      CONFIGSERVER_URI:         "http://config-server:8762"
#      KAFKASERVER_URI:          "kafka-server"
#      ZKSERVER_URI:             "kafka-server"
#      AUTHSERVER_URI:           "http://authentication-service:8764/api/v1/auth/user"
#      ZIPKIN_PORT:              "9411"
#      SERVER_PORT:              "9200"
#      KAFKASERVER_PORT:         "9092"
#      EUREKASERVER_PORT:        "8761"
#      CONFIGSERVER_PORT:        "8762"
#      ZUULSERVER_PORT:          "8763"
#      AUTHSERVER_PORT:          "8764"
#      DATABASESERVER_PORT:      "5432"
#      ZKSERVER_PORT:            "2181"
#      ENCRYPT_KEY:              "IMSYMMETRIC"
#
#  campaign-service:
#    image: gohelpfund/ghf-campaign-service:${BUILD_NAME}
#    mem_limit: 553741824
#    ports:
#    -                           "9100:9100"
#    environment:
#      PROFILE:                  "local-api"
#      EUREKASERVER_URI:         "http://eureka-server:8761/eureka/"
#      ZIPKIN_URI:               "http://zipkin-server:9411"
#      CONFIGSERVER_URI:         "http://config-server:8762"
#      KAFKASERVER_URI:          "kafka-server"
#      ZKSERVER_URI:             "kafka-server"
#      AUTHSERVER_URI:           "http://authentication-service:8764/api/v1/auth/user"
#      ZIPKIN_PORT:              "9411"
#      SERVER_PORT:              "9100"
#      KAFKASERVER_PORT:         "9092"
#      EUREKASERVER_PORT:        "8761"
#      CONFIGSERVER_PORT:        "8762"
#      ZUULSERVER_PORT:          "8763"
#      AUTHSERVER_PORT:          "8764"
#      REDIS_PORT:               "6379"
#      DATABASESERVER_PORT:      "5432"
#      ZKSERVER_PORT:            "2181"
#      ENCRYPT_KEY:              "IMSYMMETRIC"
#
#  kafka-server:
#    image: spotify/kafka
#    mem_limit: 353741824
#    ports:
#    -                             "2181:2181"
#    -                             "9092:9092"
#
#  redis:
#    image: redis:alpine
#    mem_limit: 353741824
#    ports:
#    -                             "6379:6379"
#
#  logspout:
#    image: gliderlabs/logspout
#    mem_limit: 553741824
#    command: syslog://logs7.papertrailapp.com:11494
#    environment:
#      COMPOSE_CONVERT_WINDOWS_PATHS: 1
#    volumes:
#    - /var/run/docker.sock:/var/run/docker.sock

#  category-service:
#    image: gohelpfund/ghf-category-service:${BUILD_NAME}
#    mem_limit: 353741824
#    ports:
#    - "9101:9101"
#    environment:
#      PROFILE: "local-api"
#      EUREKASERVER_URI: "http://eureka-server:8761/eureka/"
#      CONFIGSERVER_URI: "http://config-server:8762"
#      SERVER_PORT:         "9101"
#      EUREKASERVER_PORT:   "8761"
#      CONFIGSERVER_PORT:   "8762"
#      ZUULSERVER_PORT:     "8763"
#      DATABASESERVER_PORT: "5432"
#      FUNDRAISERSERVICE_PORT: "9200"
#      ENCRYPT_KEY:       "IMSYMMETRIC"

#  category-service-ab-testing:
#    image: gohelpfund/ghf-category-service-ab-testing:${BUILD_NAME}
#    mem_limit: 553741824
#    ports:
#    - "9102:9102"
#    environment:
#      PROFILE: "local-api"
#      EUREKASERVER_URI: "http://eureka-server:8761/eureka/"
#      CONFIGSERVER_URI: "http://config-server:8762"
#      SERVER_PORT:         "9102"
#      EUREKASERVER_PORT:   "8761"
#      CONFIGSERVER_PORT:   "8762"
#      DATABASESERVER_PORT: "5432"
#      ENCRYPT_KEY:       "IMSYMMETRIC"

#  upload-service:
#    image: gohelpfund/ghf-upload-service:${BUILD_NAME}
#    mem_limit: 353741824
#    ports:
#    - "9001:9001"
#    environment:
#      PROFILE: "local-api"
#      EUREKASERVER_URI: "http://eureka-server:8761/eureka/"
#      CONFIGSERVER_URI: "http://config-server:8762"
#      SERVER_PORT:         "9001"
#      EUREKASERVER_PORT:   "8761"
#      CONFIGSERVER_PORT:   "8762"
#      ZUULSERVER_PORT:     "8763"
#      DATABASESERVER_PORT: "5432"
#      FUNDRAISERSERVICE_PORT: "9200"
#      CATEGORYSERVICE_PORT: "9101"
#      ENCRYPT_KEY:       "IMSYMMETRIC"

#  specialroutes-service:
#    image: gohelpfund/ghf-specialroutes-service:${BUILD_NAME}
#    mem_limit: 553741824
#    ports:
#    - "9002:9002"
#    environment:
#      PROFILE: "local-api"
#      CONFIGSERVER_URI: "http://config-server:8888"
#      EUREKASERVER_URI: "http://eureka-server:8761/eureka/"
#      SERVER_PORT:              "9002"
#      EUREKASERVER_PORT:        "8761"
#      CONFIGSERVER_PORT:        "8762"
#      DATABASESERVER_PORT:      "5432"
#      ENCRYPT_KEY:       "IMSYMMETRIC"