version: '2'
services:
  eureka-server:
    image:   gohelpfund/ghf-eureka-server:latest
    mem_limit: 753741824
    ports:
    - "8761:8761"
  config-server:
    image: gohelpfund/ghf-config-server:latest
    mem_limit: 753741824
    ports:
    - "9000:9000"
    environment:
      PROFILE: "local-api"
      SERVER_PORT: "9000"
      EUREKASERVER_URI: "http://eureka-server:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  database:
    image: postgres:9.5
    mem_limit: 253741824
    ports:
    - "5432:5432"
    environment:
      PROFILE: "local-api"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr@s
      POSTGRES_DB: gohelpfund_local
  campaign-service:
    image: gohelpfund/ghf-campaign-service:latest
    mem_limit: 553741824
    ports:
    - "9100:9100"
    environment:
      PROFILE: "local-api"
      SERVER_PORT: "9100"
      EUREKASERVER_URI: "http://eureka-server:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_URI: "http://config-server:9000"
      CONFIGSERVER_PORT:   "9000"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  fundraiser-service:
    image: gohelpfund/ghf-fundraiser-service:latest
    mem_limit: 553741824
    ports:
    - "9200:9200"
    environment:
      PROFILE: "local-api"
      SERVER_PORT: "9200"
      EUREKASERVER_URI: "http://eureka-server:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_URI: "http://config-server:9000"
      CONFIGSERVER_PORT:   "9000"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  category-service:
    image: gohelpfund/ghf-category-service:latest
    mem_limit: 553741824
    ports:
    - "9101:9101"
    environment:
      PROFILE: "local-api"
      SERVER_PORT: "9101"
      EUREKASERVER_URI: "http://eureka-server:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_URI: "http://config-server:9000"
      CONFIGSERVER_PORT:   "9000"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  upload-service:
    image: gohelpfund/ghf-upload-service:latest
    mem_limit: 553741824
    ports:
    - "9001:9001"
    environment:
      PROFILE: "local-api"
      SERVER_PORT: "9001"
      EUREKASERVER_URI: "http://eureka-server:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_URI: "http://config-server:9000"
      CONFIGSERVER_PORT:   "9000"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"